# Application Config
server:
  port : 8081

spring:
  application:
    name: JBT-Beginner-Microservice
  # Eureka Config
eureka:
  client:
    eureka-server-port: 8761
  instance:
    health-check-url-path: /manage/health
    status-page-url-path: /manage/info

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: custEndPoint,health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: JBT-SPRING-BOOT-SAMPLE-APP
    version: v1.0

downstream:
  app:
    url: http://localhost:8761/actuator/health

app:
  name: Spring-Boot-Sample-App
  Author:
    name: JBT
    Website: javabeginnerstutorial.com
    email: admin@javabeginnerstutorial.com
  spring-version: 2.1.0.RELEASE
  java-version: 1.8